server:
  port: 8081

# Configurações Eureka
eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# Configurações Actuator
management:
  endpoints:
    web:
      base-path: /actuator
  health:
    binders:
      enabled:
        false
