server:
  port: 8081

spring:
  zipkin: http://127.0.0.1:9411/

# Configurações Eureka
eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# Configurações Actuator
management:
  endpoints:
    web:
      base-path: /actuator
  health:
    binders:
      enabled:
        false
